"""Finished text as a polished standalone HTML article (`render`, default on).

One fixed template (templates/article.html) so every text factual-research
delivers looks the same: title block with verification score, table of
contents, serif reading column, citation chips that open the verbatim
anchor quote, generated tables, reference list, evidence strength and a
short "how this was verified" appendix. No external files or requests."""
from __future__ import annotations

import datetime as dt
import html as H
import json
import re
import unicodedata
from pathlib import Path

from . import __version__
from . import tables as T
from .citations import CITE_BLOCK, TABLE_TAG, cite_items
from .evidence import summarize_claim
from .export import NUMERIC, _loc_fmt, intext_author, reference
from .model import DESIGNS, Work
from .project import Plan
from .store import INCLUDED, Store

TEMPLATE = Path(__file__).parent / "templates" / "article.html"

STRINGS = {
    "en": {
        "eyebrow": "Research brief with verified sources", "skip": "Skip to text", "top": "Back to top",
        "theme": "Switch light or dark theme", "print": "Print or save as PDF", "close": "Close",
        "contents": "Contents", "references": "References", "evidence": "Strength of evidence",
        "method": "How this text was verified", "date": "Date", "sources": "Sources", "verification": "Verification",
        "style": "Citation style", "cited": "cited", "fulltext_n": "checked on full text", "pass": "passed",
        "fail": "not passed", "question": "Research question", "search": "Search",
        "queries": "queries in", "screening": "Screening", "screened": "unique records screened",
        "included": "included", "loc": "Location", "verified": "quote verified in the source",
        "verified_ft": "quote verified in the full text", "goto": "Go to reference", "unknown": "Unknown source",
        "back": "Back to first citation", "studies": "studies", "certainty": "certainty",
        "fulltext": "full text", "abstract": "abstract only", "metadata": "metadata only", "retracted": "RETRACTED",
        "high": "high", "moderate": "moderate", "low": "low", "very low": "very low",
        "c_support": "Support", "c_numbers": "Numbers", "c_coverage": "Coverage", "c_quotes": "Quotes",
        "c_calibration": "Calibration", "c_balance_scope": "Balance and scope", "c_evidence_table": "Evidence table",
        "method_intro": ("Every citation in this text points to a source that was found in trusted databases, "
                         "screened and checked for retractions. factual-research compared each anchor quote, number and "
                         "citation with the source text before this page was generated. Open a citation to read "
                         "the exact source words."),
        "colophon": "Generated by factual-research {v} on {d}. Automatic verification does not replace expert review.",
        "evidence_note": "Certainty is a GRADE-style rating from study design, consistency and risk of bias.",
    },
    "pl": {
        "eyebrow": "Opracowanie ze zweryfikowanymi źródłami", "skip": "Przejdź do tekstu", "top": "Na górę",
        "theme": "Przełącz jasny lub ciemny motyw", "print": "Drukuj lub zapisz jako PDF", "close": "Zamknij",
        "contents": "Spis treści", "references": "Bibliografia", "evidence": "Siła dowodów",
        "method": "Jak zweryfikowano ten tekst", "date": "Data", "sources": "Źródła", "verification": "Weryfikacja",
        "style": "Styl cytowania", "cited": "cytowanych", "fulltext_n": "sprawdzonych na pełnym tekście",
        "pass": "zaliczona", "fail": "niezaliczona", "question": "Pytanie badawcze", "search": "Wyszukiwanie",
        "queries": "zapytań w", "screening": "Selekcja", "screened": "unikalnych rekordów przejrzanych",
        "included": "włączonych", "loc": "Miejsce", "verified": "cytat potwierdzony w źródle",
        "verified_ft": "cytat potwierdzony w pełnym tekście", "goto": "Przejdź do bibliografii",
        "unknown": "Nieznane źródło", "back": "Wróć do pierwszego cytowania", "studies": "badań",
        "certainty": "pewność", "fulltext": "pełny tekst", "abstract": "tylko abstrakt", "metadata": "tylko metadane",
        "retracted": "WYCOFANA", "high": "wysoka", "moderate": "umiarkowana", "low": "niska", "very low": "bardzo niska",
        "c_support": "Poparcie", "c_numbers": "Liczby", "c_coverage": "Pokrycie", "c_quotes": "Cytaty",
        "c_calibration": "Kalibracja", "c_balance_scope": "Równowaga i zakres", "c_evidence_table": "Tabela dowodów",
        "method_intro": ("Każde cytowanie w tym tekście prowadzi do źródła znalezionego w zaufanych bazach, "
                         "przejrzanego i sprawdzonego pod kątem wycofania. Przed wygenerowaniem strony factual-research "
                         "porównał każdy cytat kotwiczący, liczbę i odwołanie z tekstem źródła. Kliknij cytowanie, "
                         "aby zobaczyć dokładne słowa ze źródła."),
        "colophon": "Wygenerowano przez factual-research {v}, {d}. Automatyczna weryfikacja nie zastępuje recenzji eksperckiej.",
        "evidence_note": "Pewność to ocena w stylu GRADE oparta na typie badań, spójności wyników i ryzyku błędu.",
    },
}

DESIGNS_PL = {
    "guideline": "Wytyczne / konsensus", "sr_ma": "Przegląd systematyczny / metaanaliza",
    "rct": "Badanie randomizowane (RCT)", "clinical_trial": "Badanie kliniczne nierandomizowane",
    "cohort": "Badanie kohortowe", "case_control": "Badanie kliniczno-kontrolne",
    "cross_sectional": "Badanie przekrojowe", "observational": "Badanie obserwacyjne",
    "case_report": "Opis przypadku", "narrative_review": "Przegląd narracyjny", "animal": "Badanie na zwierzętach",
    "in_vitro": "Badanie in vitro", "trial_registration": "Rejestracja badania (bez wyników)",
    "standard": "Norma techniczna", "technical_report": "Raport techniczny",
    "journal_article": "Artykuł recenzowany", "conference_paper": "Referat konferencyjny",
    "preprint": "Preprint (bez recenzji)", "book": "Książka / rozdział", "thesis": "Praca dyplomowa",
    "dataset": "Dane / statystyka", "legislation": "Akt prawny", "judgment": "Orzeczenie",
    "editorial": "Komentarz / list", "other": "Inne",
}

MONTHS_PL = ["stycznia", "lutego", "marca", "kwietnia", "maja", "czerwca", "lipca", "sierpnia",
             "września", "października", "listopada", "grudnia"]

CONCLUSION = re.compile(r"^(wnioski|podsumowanie|konkluzj\w*|conclusions?|summary|bottom line)\b", re.I)


def e(s) -> str:
    return H.escape("" if s is None else str(s))


def detect_lang(text: str, fallback: str = "en") -> str:
    """Polish if Polish diacritics are frequent; otherwise the fallback."""
    letters = sum(c.isalpha() for c in text) or 1
    pl = len(re.findall(r"[ąćęłńóśźżĄĆĘŁŃÓŚŹŻ]", text))
    return "pl" if pl / letters > 0.004 else fallback


def slug(s: str, used: set[str]) -> str:
    s = s.replace("ł", "l").replace("Ł", "L")
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode()
    s = re.sub(r"[^a-zA-Z0-9]+", "-", s).strip("-").lower()[:60] or "s"
    base, i = s, 2
    while s in used:
        s, i = f"{base}-{i}", i + 1
    used.add(s)
    return s


def _date(lang: str) -> str:
    d = dt.date.today()
    return f"{d.day} {MONTHS_PL[d.month - 1]} {d.year}" if lang == "pl" else f"{d:%B} {d.day}, {d.year}"


def short_author(w: Work) -> str:
    """In-text author, with long organisation names cut to their acronyms
    ("EFSA Panel on Nutrition, ... (NDA)" -> "EFSA NDA Panel")."""
    a = intext_author(w)
    if len(a) <= 32:
        return a
    first = w.authors[0] if w.authors else a
    caps = [t for t in re.findall(r"\b[A-Z][A-Z0-9]{1,}\b", first)]
    if caps:
        short = " ".join(dict.fromkeys(caps)) + (" Panel" if re.search(r"\bPanel\b", first) else "")
        return short + (" et al." if a.endswith("et al.") else "")
    return a[:30].rsplit(" ", 1)[0] + "..."


def _nbsp(s: str, lang: str) -> str:
    """Polish typesetting: keep one-letter words off line ends (a, i, o, u, w, z)."""
    if lang != "pl":
        return s
    return re.sub(r"(?<![^\s(])([aiouwzAIOUWZ]) +", "\\1\u00a0", s)


def _inline(s: str) -> str:
    """Escaped markdown inline formatting (tokens like @@CG3@@ pass through)."""
    s = e(s)
    s = re.sub(r"`([^`]+)`", r"<code>\1</code>", s)
    s = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", s)
    s = re.sub(r"(?<![*\w])\*(?!\s)(.+?)(?<!\s)\*(?![*\w])", r"<em>\1</em>", s)
    s = re.sub(r"(?<!\w)_(?!\s)(.+?)(?<!\s)_(?!\w)", r"<em>\1</em>", s)
    s = re.sub(r"\[([^\]]+)\]\((https?://[^)\s]+)\)", r'<a href="\2">\1</a>', s)
    return s


def _ref_html(text: str) -> str:
    s = e(text)
    s = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", s)
    s = re.sub(r"\*(.+?)\*", r"<i>\1</i>", s)
    return re.sub(r"(https?://[^\s<]+[^\s<.,;)])", r'<a href="\1">\1</a>', s)


class _Cites:
    """Citation numbering, chip HTML and the ordered key list."""

    def __init__(self, st: Store, style: str, lang: str):
        self.st, self.style, self.lang = st, style, lang
        self.numeric = style in NUMERIC
        self.order: list[str] = []
        self.works: dict[str, Work] = {}
        self.uses: dict[str, int] = {}
        self.problems: list[str] = []

    def num(self, k: str) -> int:
        if k not in self.order:
            self.order.append(k)
        return self.order.index(k) + 1

    def label(self, k: str) -> str:
        w = self.works[k]
        return f"{short_author(w)}, {w.year or 'n.d.'}"

    def table_fmt(self, k: str) -> str:
        w = self.works.get(k) or self.st.get(k)
        if not w:
            return k
        self.works[k] = w
        return f"[{self.num(k)}]" if self.numeric else self.label(k)

    def loc(self, loc: str) -> str:
        out = _loc_fmt(loc, self.style)
        if self.lang == "pl":
            out = re.sub(r"^pp?\. ", "s. ", out)
            out = re.sub(r"^sec\. ", "rozdz. ", out)
        return out

    def block(self, inner: str) -> str:
        chips = []
        for key, loc, quote in cite_items(inner):
            k = self.st.resolve(key)
            if not k:
                self.problems.append(f"unknown key @{key}")
                chips.append(f'<span class="cite unk">@{e(key)}?</span>')
                continue
            self.works[k] = self.works.get(k) or self.st.get(k)
            n = self.num(k)
            self.uses[k] = self.uses.get(k, 0) + 1
            cid = f"c-{k}-{self.uses[k]}"
            text = str(n) if self.numeric else self.label(k)
            if loc:
                text += f", {self.loc(loc)}"
            w = self.works[k]
            depth = self.st.source_text(k)[0]
            chips.append(f'<a class="cite" id="{e(cid)}" href="#ref-{e(k)}" data-key="{e(k)}" '
                         f'data-label="{e(short_author(w))} ({e(w.year or "n.d.")})" data-quote="{e(quote)}" '
                         f'data-loc="{e(self.loc(loc) if loc else "")}" data-depth="{e(depth)}">{e(text)}</a>')
        if self.numeric:
            return f'<span class="cites num">[{", ".join(chips)}]</span>'
        return f'<span class="cites">({"; ".join(chips)})</span>'


def _markdown(text: str, tokens: dict[str, str], lang: str = "en") -> tuple[str, list[tuple[int, str, str]]]:
    """Block-level markdown to HTML. Returns (html, headings[(level, id, text)])."""
    lines = text.split("\n")
    levels = [len(m.group(1)) for m in (re.match(r"^(#{1,6})\s", l) for l in lines) if m]
    shift = 2 - min(levels) if levels else 0
    out: list[str] = []
    heads: list[tuple[int, str, str]] = []
    used: set[str] = set()
    in_concl = False
    i = 0

    def sub(s: str) -> str:
        return re.sub(r"@@CG\d+@@", lambda m: tokens.get(m.group(0), ""), _inline(_nbsp(s, lang)))

    while i < len(lines):
        s = lines[i].rstrip()
        st = s.strip()
        if not st:
            i += 1
            continue
        if st in tokens:
            out.append(tokens[st])
            i += 1
            continue
        m = re.match(r"^(#{1,6})\s+(.*)$", st)
        if m:
            lvl = max(2, min(len(m.group(1)) + shift, 4))
            raw = m.group(2).strip().rstrip("#").strip()
            plain = re.sub(r"@@CG\d+@@", "", raw).strip()
            hid = slug(plain, used)
            if lvl == 2:
                if in_concl:
                    out.append("</section>")
                    in_concl = False
                if CONCLUSION.match(plain):
                    out.append('<section class="conclusion">')
                    in_concl = True
            if lvl <= 3:
                heads.append((lvl, hid, plain))
            out.append(f'<h{lvl} id="{hid}">{sub(raw)}</h{lvl}>')
            i += 1
            continue
        if re.fullmatch(r"(-{3,}|\*{3,}|_{3,})", st):
            out.append("<hr>")
            i += 1
            continue
        if st.startswith("|"):
            rows = []
            while i < len(lines) and lines[i].strip().startswith("|"):
                cells = [c.strip() for c in lines[i].strip().strip("|").split("|")]
                if not all(re.fullmatch(r":?-{2,}:?", c) for c in cells if c):
                    rows.append(cells)
                i += 1
            if rows:
                head = "".join(f"<th>{sub(c)}</th>" for c in rows[0])
                body = "".join("<tr>" + "".join(f"<td>{sub(c)}</td>" for c in r) + "</tr>" for r in rows[1:])
                out.append(f'<figure><div class="scroll"><table><thead><tr>{head}</tr></thead>'
                           f"<tbody>{body}</tbody></table></div></figure>")
            continue
        if st.startswith(">"):
            buf = []
            while i < len(lines) and lines[i].strip().startswith(">"):
                buf.append(lines[i].strip()[1:].strip())
                i += 1
            out.append(f"<blockquote><p>{sub(' '.join(buf))}</p></blockquote>")
            continue
        lm = re.match(r"^\s*([-*+]|\d+[.)])\s+", s)
        if lm:
            tag = "ol" if lm.group(1)[0].isdigit() else "ul"
            items: list[str] = []
            while i < len(lines):
                cur = lines[i]
                im = re.match(r"^\s*([-*+]|\d+[.)])\s+(.*)$", cur)
                if im:
                    items.append(im.group(2).strip())
                elif cur.strip() and items and cur.startswith((" ", "\t")):
                    items[-1] += " " + cur.strip()
                else:
                    break
                i += 1
            out.append(f"<{tag}>" + "".join(f"<li>{sub(x)}</li>" for x in items) + f"</{tag}>")
            continue
        buf = [st]
        while i + 1 < len(lines) and lines[i + 1].strip() and not re.match(
                r"^\s*(#{1,6}\s|\||>|[-*+]\s|\d+[.)]\s|-{3,}$|@@CG\d+@@$)", lines[i + 1]):
            i += 1
            buf.append(lines[i].strip())
        out.append(f"<p>{sub(' '.join(buf))}</p>")
        i += 1
    if in_concl:
        out.append("</section>")
    return "\n".join(out), heads


def _toc(heads: list[tuple[int, str, str]], label: str, mobile: bool) -> str:
    if len(heads) < 2:
        return ""
    parts, depth = [], 0
    for lvl, hid, text in heads:
        d = 1 if lvl == 2 else 2
        if d > depth:
            parts.append("<ol>" * (d - depth))
        elif d < depth:
            parts.append("</li></ol>" * (depth - d) + "</li>")
        elif parts:
            parts.append("</li>")
        parts.append(f'<li><a href="#{hid}">{e(text)}</a>')
        depth = d
    parts.append("</li></ol>" * depth)
    lst = "".join(parts)
    if mobile:
        return f'<details class="toc toc-m"><summary>{e(label)}</summary><nav aria-label="{e(label)}">{lst}</nav></details>'
    return f'<nav class="toc toc-d" aria-label="{e(label)}"><h2>{e(label)}</h2>{lst}</nav>'


def build_article(st: Store, plan: Plan, text: str, style: str, lang: str | None = None,
                  verify_report: dict | None = None, evidence: bool = True) -> tuple[str, list[str], list[str]]:
    """Returns (html, ordered keys, problems)."""
    lang = (lang or detect_lang(text, plan.lang or "en"))[:2]
    L = STRINGS.get(lang, STRINGS["en"])
    C = _Cites(st, style, lang)
    tokens: dict[str, str] = {}

    def tok(html: str) -> str:
        t = f"@@CG{len(tokens)}@@"
        tokens[t] = html
        return t

    # title (first H1) and optional dek (a blockquote right after it)
    text = re.sub(r"<!--(?!\s*(?:fr|cg):table).*?-->", "", text, flags=re.S)
    title, dek = "", ""
    m = re.match(r"\s*#\s+(.+?)\s*\n", text + "\n")
    if m and not text.lstrip().startswith("##"):
        title = m.group(1).strip()
        text = text[m.end():]
        dm = re.match(r"\s*((?:>[^\n]*\n?)+)", text)
        if dm:
            dek = " ".join(l.strip()[1:].strip() for l in dm.group(1).strip().split("\n"))
            text = text[dm.end():]

    def table(m):
        try:
            t, pr, svg = T.placeholder_table(st, plan, m.group(1).strip().split(), lang)
        except Exception as ex:  # noqa: BLE001
            C.problems.append(f"{m.group(0)}: {ex}")
            return ""
        C.problems.extend(pr)
        if svg:
            return "\n" + tok(f'<figure class="forest">{svg}</figure>') + "\n"
        if not t:
            return ""
        html = T.table_html(t, C.table_fmt).replace('href="#src-', 'href="#ref-')
        return "\n" + tok(html) + "\n"

    combo = re.compile(TABLE_TAG + "|" + CITE_BLOCK.pattern)

    def dispatch(m):
        if m.group(0).startswith("<!--"):
            return table(m)
        return tok(C.block(re.match(CITE_BLOCK.pattern, m.group(0)).group(1)))

    text = combo.sub(dispatch, text)
    title_html = re.sub(r"@@CG\d+@@", lambda m: tokens[m.group(0)], _inline(_nbsp(title, lang))) if title else e(plan.question)
    title_text = re.sub(r"\s+", " ", re.sub(r"<[^>]+>", "", title_html))
    title_text = H.unescape(title_text).replace("\u00a0", " ")
    body, heads = _markdown(text, tokens, lang)

    # references
    keys = C.order if C.numeric else sorted(C.order, key=lambda k: (short_author(C.works[k]).lower(), C.works[k].year or 0))
    refs = []
    dnames = DESIGNS_PL if lang == "pl" else DESIGNS
    for i, k in enumerate(keys, 1):
        w = C.works[k]
        depth = st.source_text(k)[0]
        tags = [f'<span class="tag">{e(dnames.get(w.design, DESIGNS.get(w.design, w.design)))}</span>'] if w.design else []
        tags.append(f'<span class="tag">{e(L.get(depth, depth))}</span>')
        if w.is_retracted:
            tags.append(f'<span class="tag r">{e(L["retracted"])}</span>')
        back = f'<a class="back" href="#c-{e(k)}-1" aria-label="{e(L["back"])}">&#8617;</a>' if C.uses.get(k) else ""
        refs.append(f'<li id="ref-{e(k)}"><span class="n">{i}.</span><div><span class="rt">{_ref_html(reference(w, style))}</span>'
                    f'{back}<div class="tags">{"".join(tags)}</div></div></li>')
    refs_html = (f'<h2 id="bibliografia">{e(L["references"])}</h2><ol class="refs{"" if C.numeric else " ay"}">'
                 + "".join(refs) + "</ol>") if refs else ""
    if refs:
        heads.append((2, "bibliografia", L["references"]))

    # evidence strength (claims from the matrix)
    ev_html = ""
    claims = st.claims() if evidence else []
    if claims:
        combined = plan.combined()
        works = {k: w for k, _, w in st.works()}
        items = []
        for c in claims:
            s = summarize_claim(c, st.evidence(c["id"]), works, combined)
            cls = s.certainty.replace(" ", "")
            items.append(f'<li><span>{e(c["text"])}</span><span class="pill {e(cls)}">{e(L["certainty"])}: '
                         f'{e(L.get(s.certainty, s.certainty))}</span><span class="why">{s.n} {e(L["studies"])} · '
                         f'&#10004; {len(s.keys_for)} &#10008; {len(s.keys_against)} &#8776; {len(s.keys_mixed)}</span></li>')
        ev_html = (f'<h2 id="sila-dowodow">{e(L["evidence"])}</h2><ul class="ev">{"".join(items)}</ul>'
                   f'<p class="note">{e(L["evidence_note"])}</p>')
        heads.append((2, "sila-dowodow", L["evidence"]))

    # how it was verified
    from . import prisma
    pc = prisma.counts(st)
    included = st.works(status=INCLUDED)
    conns = sorted({q["connector"] for q in st.queries()})
    n_ft = sum(1 for k in keys if st.source_text(k)[0] == "fulltext")
    dl = [(L["question"], e(plan.question)),
          (L["search"], f'{len(st.queries())} {e(L["queries"])} {len(conns)}: {e(", ".join(conns))}'),
          (L["screening"], f'{pc["screened"]} {e(L["screened"])}, {len(included)} {e(L["included"])}')]
    bars = ""
    vr = verify_report
    if vr:
        bars = '<div class="bars">' + "".join(
            f'<div><span>{e(L.get("c_" + k, k))}</span><i><b style="width:{max(0, min(100, v)):.0f}%"></b></i>'
            f'<span>{v:.0f}</span></div>' for k, v in vr["components"].items()) + "</div>"
    method_html = (f'<h2 id="weryfikacja">{e(L["method"])}</h2><div class="method"><p>{e(L["method_intro"])}</p>'
                   f'<dl>{"".join(f"<dt>{e(a)}</dt><dd>{b}</dd>" for a, b in dl)}</dl>{bars}</div>')
    heads.append((2, "weryfikacja", L["method"]))

    # header metadata
    meta = [(L["date"], e(_date(lang))),
            (L["sources"], f'{len(keys)} {e(L["cited"])}<br>{n_ft} {e(L["fulltext_n"])}')]
    if vr:
        ok = vr["pass"]
        meta.append((L["verification"],
                     f'<span class="score{"" if ok else " fail"}"><span class="ring" style="--p:{vr["score"]:.0f}" aria-hidden="true">'
                     f'</span><span>{vr["score"]:.0f}/100</span></span> <span class="pill {"ok" if ok else "fail"}">'
                     f'{e(L["pass"] if ok else L["fail"])}</span>'))
    meta.append((L["style"], e(style.upper() if len(style) <= 4 else style.title())))
    meta_html = "".join(f"<div><dt>{e(a)}</dt><dd>{b}</dd></div>" for a, b in meta)

    strings = {k: L[k] for k in ("loc", "verified", "verified_ft", "goto", "unknown")}
    fill = {
        "lang": e(lang), "version": e(__version__), "title_text": e(title_text), "title": title_html,
        "description": e((dek or plan.question)[:300]), "eyebrow": e(L["eyebrow"]),
        "dek": f'<p class="dek">{_inline(_nbsp(dek, lang))}</p>' if dek else "",
        "meta": meta_html, "toc_desktop": _toc(heads, L["contents"], False), "toc_mobile": _toc(heads, L["contents"], True),
        "body": body, "references": refs_html, "evidence": ev_html, "method": method_html,
        "colophon": e(L["colophon"].format(v=__version__, d=_date(lang))),
        "strings_json": json.dumps(strings, ensure_ascii=False).replace("</", "<\\/"),
        "t_skip": e(L["skip"]), "t_top": e(L["top"]), "t_theme": e(L["theme"]), "t_print": e(L["print"]),
        "t_close": e(L["close"]),
    }
    tpl = TEMPLATE.read_text(encoding="utf-8")
    html = re.sub(r"\{\{(\w+)\}\}", lambda m: fill.get(m.group(1), ""), tpl)
    return html, C.order, C.problems
